// This file is @generated by prost-build.
/// 22bit // 13 + 4 + 5
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Date {
    #[prost(fixed32, tag = "1")]
    pub value: u32,
}
